version: '3.8'

services:
  pocketbase:
    build:
      context: ./backend
    networks:
      - myapp-network
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pocketbase.db:/app/pocketbase.db

  sveltekit:
    build:
      context: ./frontend
    networks:
      - myapp-network
    ports:
      - "3000:3000"

networks:
  myapp-network:
    external: true